name: Build and Publish
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Extract Version
        id: version
        run: |
          VERSION=$(grep '__version__' __version__.py | cut -d '"' -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --windowed --icon=assets/cost_estimate_icon_213134.ico src/main.py
          else
            pyinstaller --windowed --name MyApp --icon assets/cost_estimate_icon_213134.icns --osx-bundle-identifier src/main.py
          fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}_Build
          path: dist/
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release v${{ steps.version.outputs.version }}"
          files: |
            dist/*.exe
            dist/*.dmg
          body: "Release v${{ steps.version.outputs.version }}"