name: Build Cross-Platform Release

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name "Estimate-Generator_Win" src/main.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: Estimate-Generator_Win
        path: dist/Estimate-Generator_Win.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name "Estimate-Generator_MacOS" src/main.py

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: Estimate-Generator_MacOS
        path: dist/Estimate-Generator_MacOS

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: Estimate-Generator_Win

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: Estimate-Generator_MacOS

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Estimate-Generator_Win.exe
          Estimate-Generator_MacOS
        body: |
          Cross-platform release built from main branch
          
          **Downloads:**
          - `Estimate-Generator_Win.exe`
          - `Estimate-Generator_MacOS`